# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'FacDataV2mKUuwg.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

#from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
#    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
# from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
#     QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
#     QPixmap, QRadialGradient)
#from PySide2.QtWidgets import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(900, 700)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(37, 37, 37, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(56, 56, 56, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(46, 46, 46, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(18, 18, 18, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(25, 25, 25, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush6 = QBrush(QColor(0, 0, 0, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        brush7 = QBrush(QColor(255, 255, 220, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        brush8 = QBrush(QColor(255, 255, 255, 128))
        brush8.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(True)
        self.actionImport = QAction(MainWindow)
        self.actionImport.setObjectName(u"actionImport")
        self.actionExport = QAction(MainWindow)
        self.actionExport.setObjectName(u"actionExport")
        self.actionReset = QAction(MainWindow)
        self.actionReset.setObjectName(u"actionReset")
        self.actionRefresh = QAction(MainWindow)
        self.actionRefresh.setObjectName(u"actionRefresh")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.LeftFrame = QFrame(self.centralwidget)
        self.LeftFrame.setObjectName(u"LeftFrame")
        self.LeftFrame.setGeometry(QRect(0, 0, 450, 650))
        sizePolicy.setHeightForWidth(self.LeftFrame.sizePolicy().hasHeightForWidth())
        self.LeftFrame.setSizePolicy(sizePolicy)
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        brush9 = QBrush(QColor(133, 131, 134, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush9)
        brush10 = QBrush(QColor(200, 197, 202, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush10)
        brush11 = QBrush(QColor(166, 164, 168, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush11)
        brush12 = QBrush(QColor(66, 65, 67, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush12)
        brush13 = QBrush(QColor(89, 87, 89, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush13)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush6)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush6)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush9)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        brush14 = QBrush(QColor(194, 193, 194, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush14)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        brush15 = QBrush(QColor(0, 0, 0, 128))
        brush15.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush15)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush10)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush11)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush12)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush13)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush14)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush15)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush12)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush10)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush11)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush12)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush13)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush12)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush12)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush15)
#endif
        self.LeftFrame.setPalette(palette1)
        self.LeftFrame.setAutoFillBackground(True)
        self.LeftFrame.setFrameShape(QFrame.StyledPanel)
        self.LeftFrame.setFrameShadow(QFrame.Plain)
        self.LeftFrame.setLineWidth(1)
        self.verticalLayoutWidget = QWidget(self.LeftFrame)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 10, 431, 367))
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.lineEdit_10 = QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        palette2 = QPalette()
        brush16 = QBrush(QColor(48, 49, 50, 63))
        brush16.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Highlight, brush16)
        palette2.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.Highlight, brush16)
        palette2.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush6)
        brush17 = QBrush(QColor(70, 70, 70, 255))
        brush17.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Disabled, QPalette.Highlight, brush17)
        palette2.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        self.lineEdit_10.setPalette(palette2)
        self.lineEdit_10.setInputMethodHints(Qt.ImhNone)
        self.lineEdit_10.setFrame(True)
        self.lineEdit_10.setClearButtonEnabled(False)

        self.gridLayout.addWidget(self.lineEdit_10, 6, 1, 1, 1)

        self.lineEdit_3 = QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.Highlight, brush16)
        palette3.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.Highlight, brush16)
        palette3.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.Highlight, brush17)
        palette3.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        self.lineEdit_3.setPalette(palette3)
        self.lineEdit_3.setClearButtonEnabled(False)

        self.gridLayout.addWidget(self.lineEdit_3, 1, 3, 1, 1)

        self.lineEdit_2 = QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.Highlight, brush16)
        palette4.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette4.setBrush(QPalette.Inactive, QPalette.Highlight, brush16)
        palette4.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush6)
        palette4.setBrush(QPalette.Disabled, QPalette.Highlight, brush17)
        palette4.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        self.lineEdit_2.setPalette(palette4)
        self.lineEdit_2.setClearButtonEnabled(False)

        self.gridLayout.addWidget(self.lineEdit_2, 1, 2, 1, 1)

        self.label_3 = QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFrameShadow(QFrame.Raised)
        self.label_3.setTextFormat(Qt.PlainText)
        self.label_3.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)

        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)

        self.lineEdit_5 = QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.Highlight, brush16)
        palette5.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.Highlight, brush16)
        palette5.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush6)
        palette5.setBrush(QPalette.Disabled, QPalette.Highlight, brush17)
        palette5.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        self.lineEdit_5.setPalette(palette5)
        self.lineEdit_5.setClearButtonEnabled(False)

        self.gridLayout.addWidget(self.lineEdit_5, 2, 2, 1, 1)

        self.label_9 = QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setFrameShadow(QFrame.Raised)
        self.label_9.setTextFormat(Qt.PlainText)
        self.label_9.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)

        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)

        self.label = QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(u"label")
        self.label.setFrameShape(QFrame.NoFrame)
        self.label.setTextFormat(Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)

        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout.addItem(self.verticalSpacer_2, 4, 0, 1, 1)

        self.lineEdit_6 = QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.Highlight, brush16)
        palette6.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.Highlight, brush16)
        palette6.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.Highlight, brush17)
        palette6.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        self.lineEdit_6.setPalette(palette6)
        self.lineEdit_6.setClearButtonEnabled(False)

        self.gridLayout.addWidget(self.lineEdit_6, 2, 3, 1, 1)

        self.lineEdit_1 = QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_1.setObjectName(u"lineEdit_1")
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.Highlight, brush16)
        palette7.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette7.setBrush(QPalette.Inactive, QPalette.Highlight, brush16)
        palette7.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush6)
        palette7.setBrush(QPalette.Disabled, QPalette.Highlight, brush17)
        palette7.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        self.lineEdit_1.setPalette(palette7)
        self.lineEdit_1.setInputMethodHints(Qt.ImhNone)
        self.lineEdit_1.setFrame(True)
        self.lineEdit_1.setClearButtonEnabled(False)

        self.gridLayout.addWidget(self.lineEdit_1, 1, 1, 1, 1)

        self.lineEdit_9 = QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.Highlight, brush16)
        palette8.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.Highlight, brush16)
        palette8.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush6)
        palette8.setBrush(QPalette.Disabled, QPalette.Highlight, brush17)
        palette8.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        self.lineEdit_9.setPalette(palette8)
        self.lineEdit_9.setClearButtonEnabled(False)

        self.gridLayout.addWidget(self.lineEdit_9, 3, 3, 1, 1)

        self.label_2 = QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setFrameShadow(QFrame.Raised)
        self.label_2.setTextFormat(Qt.PlainText)
        self.label_2.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)

        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)

        self.label_4 = QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setFrameShadow(QFrame.Raised)
        self.label_4.setTextFormat(Qt.PlainText)
        self.label_4.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)

        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)

        self.lineEdit_7 = QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.Highlight, brush16)
        palette9.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette9.setBrush(QPalette.Inactive, QPalette.Highlight, brush16)
        palette9.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush6)
        palette9.setBrush(QPalette.Disabled, QPalette.Highlight, brush17)
        palette9.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        self.lineEdit_7.setPalette(palette9)
        self.lineEdit_7.setClearButtonEnabled(False)

        self.gridLayout.addWidget(self.lineEdit_7, 3, 1, 1, 1)

        self.label_6 = QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setFrameShadow(QFrame.Raised)
        self.label_6.setTextFormat(Qt.PlainText)
        self.label_6.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)

        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)

        self.lineEdit_11 = QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.Highlight, brush16)
        palette10.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette10.setBrush(QPalette.Inactive, QPalette.Highlight, brush16)
        palette10.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush6)
        palette10.setBrush(QPalette.Disabled, QPalette.Highlight, brush17)
        palette10.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        self.lineEdit_11.setPalette(palette10)
        self.lineEdit_11.setInputMethodHints(Qt.ImhNone)
        self.lineEdit_11.setFrame(True)
        self.lineEdit_11.setClearButtonEnabled(False)

        self.gridLayout.addWidget(self.lineEdit_11, 7, 1, 1, 1)

        self.lineEdit_8 = QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.Highlight, brush16)
        palette11.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette11.setBrush(QPalette.Inactive, QPalette.Highlight, brush16)
        palette11.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush6)
        palette11.setBrush(QPalette.Disabled, QPalette.Highlight, brush17)
        palette11.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        self.lineEdit_8.setPalette(palette11)
        self.lineEdit_8.setClearButtonEnabled(False)

        self.gridLayout.addWidget(self.lineEdit_8, 3, 2, 1, 1)

        self.label_5 = QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setFrameShadow(QFrame.Raised)
        self.label_5.setTextFormat(Qt.PlainText)
        self.label_5.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)

        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)

        self.label_8 = QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setFrameShadow(QFrame.Raised)
        self.label_8.setTextFormat(Qt.PlainText)
        self.label_8.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)

        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)

        self.label_7 = QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setFrameShadow(QFrame.Raised)
        self.label_7.setTextFormat(Qt.PlainText)
        self.label_7.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)

        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)

        self.lineEdit_4 = QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.Highlight, brush16)
        palette12.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette12.setBrush(QPalette.Inactive, QPalette.Highlight, brush16)
        palette12.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush6)
        palette12.setBrush(QPalette.Disabled, QPalette.Highlight, brush17)
        palette12.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        self.lineEdit_4.setPalette(palette12)
        self.lineEdit_4.setClearButtonEnabled(False)

        self.gridLayout.addWidget(self.lineEdit_4, 2, 1, 1, 1)

        self.lineEdit_12 = QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.Highlight, brush16)
        palette13.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette13.setBrush(QPalette.Inactive, QPalette.Highlight, brush16)
        palette13.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush6)
        palette13.setBrush(QPalette.Disabled, QPalette.Highlight, brush17)
        palette13.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        self.lineEdit_12.setPalette(palette13)
        self.lineEdit_12.setInputMethodHints(Qt.ImhNone)
        self.lineEdit_12.setFrame(True)
        self.lineEdit_12.setClearButtonEnabled(False)

        self.gridLayout.addWidget(self.lineEdit_12, 8, 1, 1, 1)

        self.label_10 = QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setFrameShape(QFrame.NoFrame)
        self.label_10.setTextFormat(Qt.AutoText)
        self.label_10.setScaledContents(False)
        self.label_10.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_10, 5, 1, 1, 1)

        self.lineEdit_13 = QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.Highlight, brush16)
        palette14.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette14.setBrush(QPalette.Inactive, QPalette.Highlight, brush16)
        palette14.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush6)
        palette14.setBrush(QPalette.Disabled, QPalette.Highlight, brush17)
        palette14.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        self.lineEdit_13.setPalette(palette14)
        self.lineEdit_13.setInputMethodHints(Qt.ImhNone)
        self.lineEdit_13.setFrame(True)
        self.lineEdit_13.setClearButtonEnabled(False)

        self.gridLayout.addWidget(self.lineEdit_13, 6, 2, 1, 1)

        self.label_11 = QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setFrameShape(QFrame.NoFrame)
        self.label_11.setTextFormat(Qt.AutoText)
        self.label_11.setScaledContents(False)
        self.label_11.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_11, 5, 2, 1, 1)


        self.verticalLayout_2.addLayout(self.gridLayout)

        self.line = QFrame(self.verticalLayoutWidget)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)

        self.verticalLayout_2.addWidget(self.line)

        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.pushButton_Clear = QPushButton(self.verticalLayoutWidget)
        self.pushButton_Clear.setObjectName(u"pushButton_Clear")
        self.pushButton_Clear.setFlat(False)

        self.gridLayout_2.addWidget(self.pushButton_Clear, 0, 0, 1, 1)

        self.pushButton_Refresh = QPushButton(self.verticalLayoutWidget)
        self.pushButton_Refresh.setObjectName(u"pushButton_Refresh")
        self.pushButton_Refresh.setFlat(False)

        self.gridLayout_2.addWidget(self.pushButton_Refresh, 0, 2, 1, 1)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_2.addItem(self.horizontalSpacer, 0, 3, 1, 1)

        self.pushButton_Default = QPushButton(self.verticalLayoutWidget)
        self.pushButton_Default.setObjectName(u"pushButton_Default")
        self.pushButton_Default.setFlat(False)

        self.gridLayout_2.addWidget(self.pushButton_Default, 0, 1, 1, 1)


        self.verticalLayout_2.addLayout(self.gridLayout_2)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_2.addItem(self.verticalSpacer)

        self.BottomRightFrame = QFrame(self.centralwidget)
        self.BottomRightFrame.setObjectName(u"BottomRightFrame")
        self.BottomRightFrame.setGeometry(QRect(450, 450, 450, 200))
        sizePolicy.setHeightForWidth(self.BottomRightFrame.sizePolicy().hasHeightForWidth())
        self.BottomRightFrame.setSizePolicy(sizePolicy)
        self.BottomRightFrame.setFrameShape(QFrame.StyledPanel)
        self.BottomRightFrame.setFrameShadow(QFrame.Raised)
        self.TopRightFrame = QFrame(self.centralwidget)
        self.TopRightFrame.setObjectName(u"TopRightFrame")
        self.TopRightFrame.setGeometry(QRect(450, 0, 450, 450))
        sizePolicy.setHeightForWidth(self.TopRightFrame.sizePolicy().hasHeightForWidth())
        self.TopRightFrame.setSizePolicy(sizePolicy)
        self.TopRightFrame.setFrameShape(QFrame.StyledPanel)
        self.TopRightFrame.setFrameShadow(QFrame.Raised)
        self.GraphSelectorWidget = QTabWidget(self.TopRightFrame)
        self.GraphSelectorWidget.setObjectName(u"GraphSelectorWidget")
        self.GraphSelectorWidget.setGeometry(QRect(0, 0, 450, 450))
        sizePolicy.setHeightForWidth(self.GraphSelectorWidget.sizePolicy().hasHeightForWidth())
        self.GraphSelectorWidget.setSizePolicy(sizePolicy)
        self.GraphSelectorWidget.setAutoFillBackground(True)
        self.GraphSelectorWidget.setElideMode(Qt.ElideRight)
        self.GraphSelectorWidget.setUsesScrollButtons(False)
        self.GraphSelectorWidget.setDocumentMode(True)
        self.GraphSelectorWidget.setTabsClosable(False)
        self.GraphSelectorWidget.setMovable(False)
        self.GraphSelectorWidget.setTabBarAutoHide(False)
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.GraphFrame1 = QFrame(self.tab_1)
        self.GraphFrame1.setObjectName(u"GraphFrame1")
        self.GraphFrame1.setGeometry(QRect(10, 10, 430, 410))
        self.GraphFrame1.setFrameShape(QFrame.StyledPanel)
        self.GraphFrame1.setFrameShadow(QFrame.Raised)
        self.GraphSelectorWidget.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.GraphFrame2 = QFrame(self.tab_2)
        self.GraphFrame2.setObjectName(u"GraphFrame2")
        self.GraphFrame2.setGeometry(QRect(10, 10, 430, 410))
        self.GraphFrame2.setFrameShape(QFrame.StyledPanel)
        self.GraphFrame2.setFrameShadow(QFrame.Raised)
        self.GraphSelectorWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.GraphFrame3 = QFrame(self.tab_3)
        self.GraphFrame3.setObjectName(u"GraphFrame3")
        self.GraphFrame3.setGeometry(QRect(10, 10, 430, 410))
        self.GraphFrame3.setFrameShape(QFrame.StyledPanel)
        self.GraphFrame3.setFrameShadow(QFrame.Raised)
        self.GraphSelectorWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 900, 24))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuEdit.addAction(self.actionReset)
        self.menuEdit.addAction(self.actionRefresh)

        self.retranslateUi(MainWindow)

        self.GraphSelectorWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Model", None))
        self.actionImport.setText(QCoreApplication.translate("MainWindow", u"Import", None))
#if QT_CONFIG(shortcut)
        self.actionImport.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionExport.setText(QCoreApplication.translate("MainWindow", u"Export", None))
#if QT_CONFIG(shortcut)
        self.actionExport.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionReset.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
#if QT_CONFIG(shortcut)
        self.actionReset.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+X", None))
#endif // QT_CONFIG(shortcut)
        self.actionRefresh.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
#if QT_CONFIG(shortcut)
        self.actionRefresh.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R, Return", None))
#endif // QT_CONFIG(shortcut)
        self.lineEdit_10.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.lineEdit_3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.lineEdit_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Full", None))
        self.lineEdit_5.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Full", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Asst", None))
        self.lineEdit_6.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.lineEdit_1.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.lineEdit_9.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Assoc", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Asst", None))
        self.lineEdit_7.setInputMask("")
        self.lineEdit_7.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Full", None))
        self.lineEdit_11.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.lineEdit_8.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Assoc", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Assoc", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Asst", None))
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.lineEdit_12.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Initial", None))
        self.lineEdit_13.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Years", None))
        self.pushButton_Clear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.pushButton_Refresh.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.pushButton_Default.setText(QCoreApplication.translate("MainWindow", u"Default", None))
        self.GraphSelectorWidget.setTabText(self.GraphSelectorWidget.indexOf(self.tab_1), QCoreApplication.translate("MainWindow", u"Tab 1", None))
        self.GraphSelectorWidget.setTabText(self.GraphSelectorWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Tab 2", None))
        self.GraphSelectorWidget.setTabText(self.GraphSelectorWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Tab 3", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
    # retranslateUi

